import 'package:islami_app/models/radio_data_model.dart';

abstract class RadioDataConstraints {
  static List<String> reciters = [
    "Mishary Rashid Alafasy",
    "Abdul Basit Abdul Samad",
    "Mahmoud Khalil Al-Husary",
    "Saad Al-Ghamdi",
    "Maher Al-Muaiqly",
    "Yasser Al-Dosari",
    "Abdullah Awad Al-Juhany",
    "Idris Abkar",
    "Nasser Al-Qatami",
    "Ali Jaber",
    "Mohammed Siddiq Al-Minshawi",
    "Ahmad Al-Ajmi",
    "Hani Ar-Rifai",
    "Khalid Al-Jalil",
    "Abu Bakr Al-Shatri",
    "Fares Abbad",
    "Salah Bukhatir",
    "Tawfeeq As-Sayegh",
    "Muhammad Ayyub",
    "Abdul Rahman Al-Sudais",
    "Saud Al-Shuraim",
    "Mohamed Jibreel",
    "Adel Rayyan",
    "Ahmed Neana",
    "Ibrahim Al-Akhdar",
    "Ali Huthaify",
    "Ali Abdur-Rahman Al-Hudhaify",
    "Yassin Al-Jazaery",
    "Akram Al-Ajurry",
    "Omar Al-Qazabri",
  ];
  static List<String> quranRadios = [
    "Saudi Quran Radio",
    "Makkah Live Radio",
    "Madinah Live Radio",
    "Al-Quran Al-Kareem Radio - Egypt",
    "Quran Radio - Kuwait",
    "Quran Radio - UAE",
    "Quran Radio - Bahrain",
    "Quran Radio - Qatar",
    "Quran Radio - Oman",
    "Quran Radio - Jordan",
    "Quran Radio - Palestine",
    "Quran Radio - Morocco",
    "Quran Radio - Algeria",
    "Quran Radio - Tunisia",
    "Quran Radio - Sudan",
    "Quran Radio - Yemen",
    "Quran Radio - Turkey",
    "Quran Radio - Indonesia",
    "Quran Radio - Malaysia",
    "Quran Radio - Nigeria",
    "Quran Radio - Pakistan",
    "Quran Radio - Bangladesh",
    "Quran Radio - India",
    "Quran Radio - France",
    "Quran Radio - UK",
    "Quran Radio - USA",
    "Quran Radio - Canada",
    "Quran Radio - Australia",
    "Quran Kareem FM (Jordan)",
    "Quran Radio English Translation",
  ];

  static List<RadioDataModels> recitersData = List.generate(
    reciters.length,
    (index) => RadioDataModels(name: reciters[index]),
  );
  static List<RadioDataModels> radioStationsData = List.generate(
    quranRadios.length,
    (index) => RadioDataModels(name: quranRadios[index]),
  );
}
